@startuml profile_dload_init
autonumber

title §3.1.1 Profile Download Initiation (SGP.22 v3.0)
footer \n\n§3.1.1 Profile Download Initiation (SGP.22 v3.0)\n<:1f4cc:> https://www.linkedin.com/in/allanalfante/
skinparam sequenceMessageAlign center
skinparam ParticipantPadding 20
skinparam BoxPadding 10
skinparam SequenceGroupBorderColor #Navy

'''
'PARTICPANTS
''''
actor "End-User" as user
participant "Operator" as operator
database "SM-DP+" as smdp

'''
'CONTRACT SUBSCRIPTION PROCESS
''''

== Sub-process #1: §3.1.1.1 Contract subscription process (Informative) ==

note over user #Snow
Thru Operator's Point of Sale (POS) using their web portal, 
whether on a PC, your primary device's web browser, 
or a companion app on your primary device.
end note

group#TECHNOLOGY with EID and IMEI 

  alt#Gold Successful case
    user -> operator: EID, IMEI, contact details,\nuser details, payment details
   operator -> operator: Verify target device, determine\nprofileType and offer.   
  
  else <font color=red>Unsuccessful case</font>
    autonumber 2
    operator -> operator: Cannot provide appropriate profile.\nProcess stops.
    destroy operator
  end

end

group#Pink without EID and IMEI
  autonumber 1
  user -> operator: Contact details,\nuser details, payment details
  operator -> operator: Verification target device will be\nexecuted during Profile download\nand installation procedure (§3.1.3)
end

'''
'DOWNLOAD PREPARATION PROCESS
''''

== Sub-process #2: §3.1.1.2 Download preparation process ==

note over operator #Snow
<b>eid</b> is optional. If you plan to use an SM-DS or Default SM-DP+ for Profile download, 
then <b>eid</b> SHALL be present.
 
At least one of <b>iccid</b> and <b>profileType</b> SHALL be present.
- If <b>iccid</b> is given, the SM-DP+ SHALL verify that this ICCID is available.
- If <b>profileType</b> is given, the SM-DP+ SHALL pick one of the related ICCID in its inventory.
<#lightblue,#black>|=  Input Parameters  |=  Default SM-DP+  |=  Activation Code  |=  SM-DS  |
<#white>|  eid  |  O  |  O  |  O  |
<#white>|  iccid  |  O  |  O  |  O  |
<#white>|  profileType  |  C  |  C  |  C  |
end note

  operator -> smdp: The Operator calls the <font color=magenta>"ES2+.DownloadOrder"</font> (§5.3.1)\nfunction of the SM-DP+ with the relevant input data.
rnote left: HTTP POST /gsma/rsp2/es2plus/<font color=magenta>downloadOrder</font> HTTP/1.1\nHost: smdp.example.com\nUser-Agent: MyClient/1.0\nX-Admin-Protocol: gsma/rsp/v3.0.0\nContent-Type: application/json;charset=UTF-8\nContent-Length: 199\n\n{\n  "header": {\n    "functionRequesterIdentifier": "RequesterID",\n    "functionCallIdentifier": "TX-567"\n  },\n  "eid": "89001567010203040506070809101152",\n  "iccid": "8947010000123456784F",\n  "profileType": "myProfileType"\n}

  smdp -> smdp: SM-DP+ to reserve ICCID

alt#Gold Successful case: ICCID was reserved
  smdp --> operator: The SM-DP+ returns the acknowledged ICCID\n(SHALL be the same value as the received one, if any)
rnote right: HTTP/1.1 200 OK\nX-Admin-Protocol: gsma/rsp/v3.0.0\nContent-Type: application/json;charset=UTF-8\nContent-Length: 200\n\n{\n  "header": {\n    "functionExecutionStatus": {\n      "status": "Executed-Success"\n    }\n  },\n  "iccid": "8947010000123456784F"\n}

else <font color=red>Unsuccessful case</font>: No more Profile available for the requested Profile Type
autonumber 5
smdp --> operator: SM-DP+ returns an error 
rnote right: HTTP/1.1 200 OK\nX-Admin-Protocol: gsma/rsp/v3.0.0\nContent-Type: application/json;charset=UTF-8\nContent-Length: 354\n\n{\n  "header": {\n    "functionExecutionStatus": {\n      "status": "Failed",\n      "statusCodeData": {\n        "subjectCode": "8.2.5",\n        "reasonCode": "3.7",\n        "message": "No more Profile"\n      }\n    }\n  }\n}

end

operator -> operator: Operator MAY generate a matchingId (§4.1.1)\nor SM-DP+ after ES2+.ConfirmOrder call.
operator -> operator: Operator MAY perform HLR provisioning
note over operator #Snow
(1) eid is required if it is not present in ES2+.DownloadOrder
(2) matchingId must be generated by SM-DP+ for ActivationCodeToken, if not present
(3) matchingId must be generated by SM-DP+ used it as EventID, if not present
(4) One or both of smdsAddress and rootSmdsAddress SHALL be present
<#lightblue,#black>|=  Input Parameters  |=  Default SM-DP+  |=  Activation Code  |=  SM-DS  |
<#white>|  iccid  |  M  |  M  |  M  |
<#white>|  <font color=red>eid</font>  |  C<sup>1</sup>  |  <font color=red>O</font>  |  C<sup>1</sup>  |
<#white>|  matchingId  |  M  |  O<sup>2</sup>  |  O<sup>3</sup>  |
<#white>|  confirmationCode  |  O  |  O  |  O  |
<#white>|  smdsAddress  |  Not present  |  Not present  |  C<sup>4</sup>  |
<#white>|  rootSmdsAddress  |  Not present  |  Not present  |  C<sup>4</sup>  |
<#white>|  releaseFlag  |  M  |  M  |  M  |
end note

operator -> smdp: <font color=magenta>"ES2+.ConfirmOrder"</font> (§5.3.2) function is called\nwith the ICCID and its relevant input data
rnote left
POST /gsma/rsp2/es2plus/confirmOrder HTTP/1.1
Host: smdp.example.com
X-Admin-Protocol: gsma/rsp/v3.0.0
Content-Type: application/json;charset=UTF-8
Content-Length: 292
{
  "header": {
    "functionRequesterIdentifier": "RequesterID",
    "functionCallIdentifier": "TX-568"
  },
  "iccid": "8947010000123456784F",
  "eid": "89001567010203040506070809101152",
  "matchingId": "AB3C9-K8H2M-Y1R7P-0Q5ZT",
  "confirmationCode": "SHA256(WXYZ456)",
  "smdsAddress": "sm-ds.example.com",
  "rootSmdsAddress": "root-sm-ds.example.com",
  "releaseFlag": true
}
end note

opt#LightSteelBlue if matchingId was not generated\n3 steps earlier
smdp -> smdp: SM-DP+ SHALL generate matchingId
end

smdp --> operator: The SM-DP+ MAY return an SM-DP+ address value.\nOperator SHALL use this to generate the Activation Code (§4.1).
rnote right: HTTP/1.1 200 OK\nX-Admin-Protocol: gsma/rsp/v3.0.0\nContent-Type: application/json;charset=UTF-8\nContent-Length: 174\n\n{\n  "header": {\n    "functionExecutionStatus": {\n      "status": "Executed-Success"\n    }\n  },\n  "eid": "89001567010203040506070809101152",\n  "matchingId": "AB3C9-K8H2M-Y1R7P-0Q5ZT",\n  "smdpAddress": "smdp.example.com"\n}



'''
'CONTRACT FINALIZATION
''''

== Sub-process #3: §3.1.1.3 Contract Finalization (Informative) ==

alt#Gold Profile download using Activation
operator --> user: Activation Code or with optional Confirmation Code

else Profile download using SM-DS or Default SM-DP+
autonumber 11
operator --> user: informs End-User that triggers the Profile download procedure,\ne.g., the very first boot-up and/or IP connection of the device

end


'''
'SUBSCRIPTION ACTIVATION PROCESS
''''

== Sub-process #4: §3.1.1.4 Subscription activation process (Optional) ==

opt#LightSteelBlue In case, Operator did not perform\nHLR provisioning in earlier step
  operator -> operator: Operator MAY perform HLR provisioning
end

operator -> smdp: <font color=magenta>"ES2+.ReleaseProfile"</font> (§5.3.4) function with ICCID is called to allow the\ndownload and installation procedure to be started by the End User.
rnote left: HTTP POST /gsma/rsp2/es2plus/<font color=magenta>releaseProfile</font> HTTP/1.1\nHost: smdp.example.com\nX-Admin-Protocol: gsma/rsp/v3.0.0\nContent-Type: application/json;charset=UTF-8 \nContent-Length: 38\n\n{\n  "header": {\n    "functionRequesterIdentifier": "RequesterID",\n    "functionCallIdentifier": "TX-569"\n  },\n  "iccid": "8947010000123456784F"\n}

smdp --> operator: SM-DP+ returns the result
rnote right: HTTP/1.1 200 OK\nX-Admin-Protocol: gsma/rsp/v3.0.0\nContent-Type: application/json;charset=UTF-8\nContent-Length: 20\n\n{\n  "header": {\n    "functionExecutionStatus": {\n      "status": "Executed-Success"\n    }\n  }\n}
@enduml